version: '3'

volumes:
  bundle:

services:
  db:
    image: postgres:12.4
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - '.:/app'
      - bundle:/usr/local/bundle
      - ./vendor/assets/fonts:/usr/share/fonts
    ports:
      - '3000:3000'
    env_file: app.env
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true

  redis:
    image: redis:5.0.6
